TEXT_TO_IMAGE_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/txt2img.svg"
IMAGE_TO_IMAGE_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/img2img.svg"
IMAGE_TO_TEXT_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/img2txt.svg"
CONTROLNET_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/controlnet.svg"
CONTROLNET_HINT_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/wrench.svg"
SD_OUTPAINTING_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/sd-outpainting.svg"
SR_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/sr.svg"
SOD_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/sod.svg"
VARIATION_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/variation.svg"
HARMONIZATION_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/sparkle.svg"
PROMPT_ENHANCE_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/text-sparkle.svg"
WORKFLOW_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/workflow.svg"
EXECUTE_WORKFLOW_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/execute-workflow.svg"
DEFAULT_PLUGIN_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/default-plugin.svg"
DEFAULT_PLUGIN_GROUP_ICON = "https://ailab-huawei-cdn.nolibox.com/upload/static/carefree-drawboard/icons/default-plugin-group.svg"

FUSING_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FFusing.svg"
EDGEFUSING_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FEdgeFusing.svg"
BODYFUSING_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FBodyFusing.svg"
INPAINT_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2Finpaint.svg"
CNINPAINT_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FCNinpaint.svg"
EDGE_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FgetEdge.svg"
SOFTEDGE_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FgetSoftEdge.svg"
DEPTH_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FgetDepth.svg"
DETAIL_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FrepaintDetail.svg"
STYLE_ICON = "https://image-1300968464.cos.ap-shanghai.myqcloud.com/chameleon%2Ficons%2FstyleTransfer.svg"

